//go:build go1.22

// Package webapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ActionKind.
const (
	ApplyHint  ActionKind = "apply-hint"
	ClearNotes ActionKind = "clear-notes"
	ClearValue ActionKind = "clear-value"
	Redo       ActionKind = "redo"
	Repair     ActionKind = "repair"
	Reset      ActionKind = "reset"
	SetValue   ActionKind = "set-value"
	Solve      ActionKind = "solve"
	ToggleNote ActionKind = "toggle-note"
	Undo       ActionKind = "undo"
)

// Defines values for Difficulty.
const (
	Easy   Difficulty = "easy"
	Evil   Difficulty = "evil"
	Expert Difficulty = "expert"
	Hard   Difficulty = "hard"
	Medium Difficulty = "medium"
)

// Defines values for ErrorCode.
const (
	ErrorCodeForbiddenOrigin      ErrorCode = "forbidden-origin"
	ErrorCodeImmutableCell        ErrorCode = "immutable-cell"
	ErrorCodeInternalError        ErrorCode = "internal-error"
	ErrorCodeInvalidAction        ErrorCode = "invalid-action"
	ErrorCodeInvalidCell          ErrorCode = "invalid-cell"
	ErrorCodeInvalidJson          ErrorCode = "invalid-json"
	ErrorCodeInvalidRequest       ErrorCode = "invalid-request"
	ErrorCodeInvalidSession       ErrorCode = "invalid-session"
	ErrorCodeNoHint               ErrorCode = "no-hint"
	ErrorCodeNoRedo               ErrorCode = "no-redo"
	ErrorCodeNoUndo               ErrorCode = "no-undo"
	ErrorCodeNoteNotAllowed       ErrorCode = "note-not-allowed"
	ErrorCodePayloadTooLarge      ErrorCode = "payload-too-large"
	ErrorCodePersistenceFailed    ErrorCode = "persistence-failed"
	ErrorCodeRevisionConflict     ErrorCode = "revision-conflict"
	ErrorCodeSessionNotFound      ErrorCode = "session-not-found"
	ErrorCodeUnauthorized         ErrorCode = "unauthorized"
	ErrorCodeUnsupportedMediaType ErrorCode = "unsupported-media-type"
)

// Defines values for GameStatus.
const (
	InProgress GameStatus = "in-progress"
	Invalid    GameStatus = "invalid"
	Solved     GameStatus = "solved"
)

// ActionKind defines model for ActionKind.
type ActionKind string

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	union json.RawMessage
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	Result   ActionResult `json:"result"`
	Revision Revision     `json:"revision"`
	Snapshot Snapshot     `json:"snapshot"`

	// Warnings Non-fatal diagnostics produced after the game action was accepted.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ActionResult defines model for ActionResult.
type ActionResult struct {
	Action  ActionKind   `json:"action"`
	CanRedo bool         `json:"can_redo"`
	CanUndo bool         `json:"can_undo"`
	Changes []CellChange `json:"changes"`
	Hint    *Hint        `json:"hint,omitempty"`
	Status  GameStatus   `json:"status"`
}

// ApplyHintAction defines model for ApplyHintAction.
type ApplyHintAction = NoArgumentApplyHintAction

// BooleanGrid defines model for BooleanGrid.
type BooleanGrid = []BooleanRow

// BooleanRow defines model for BooleanRow.
type BooleanRow = []bool

// CellChange defines model for CellChange.
type CellChange struct {
	// After Zero represents an empty cell.
	After CellValue `json:"after"`

	// Before Zero represents an empty cell.
	Before        CellValue `json:"before"`
	Column        int       `json:"column"`
	InvalidAfter  bool      `json:"invalid_after"`
	InvalidBefore bool      `json:"invalid_before"`
	NotesAfter    DigitSet  `json:"notes_after"`
	NotesBefore   DigitSet  `json:"notes_before"`
	Row           int       `json:"row"`
}

// CellPosition defines model for CellPosition.
type CellPosition struct {
	Column int `json:"column"`
	Row    int `json:"row"`
}

// CellValue Zero represents an empty cell.
type CellValue = int

// ClearNotesAction defines model for ClearNotesAction.
type ClearNotesAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
}

// ClearValueAction defines model for ClearValueAction.
type ClearValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Source CreateSessionRequest_Source `json:"source"`
}

// CreateSessionRequest_Source defines model for CreateSessionRequest.Source.
type CreateSessionRequest_Source struct {
	union json.RawMessage
}

// Difficulty defines model for Difficulty.
type Difficulty string

// DifficultySource defines model for DifficultySource.
type DifficultySource struct {
	Difficulty Difficulty `json:"difficulty"`
	Kind       string     `json:"kind"`
}

// Digit defines model for Digit.
type Digit = int

// DigitSet defines model for DigitSet.
type DigitSet = []Digit

// DigitSetGrid defines model for DigitSetGrid.
type DigitSetGrid = []DigitSetRow

// DigitSetRow defines model for DigitSetRow.
type DigitSetRow = []DigitSet

// Error defines model for Error.
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Cell    *CellPosition `json:"cell,omitempty"`
	Code    ErrorCode     `json:"code"`
	Field   *string       `json:"field,omitempty"`
	Message string        `json:"message"`
}

// GameStatus defines model for GameStatus.
type GameStatus string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Hint defines model for Hint.
type Hint struct {
	Column    int    `json:"column"`
	Reason    string `json:"reason"`
	Row       int    `json:"row"`
	Technique string `json:"technique"`
	Value     Digit  `json:"value"`
}

// HintPreview defines model for HintPreview.
type HintPreview struct {
	Hint     Hint     `json:"hint"`
	Revision Revision `json:"revision"`
}

// NoArgumentApplyHintAction defines model for NoArgumentApplyHintAction.
type NoArgumentApplyHintAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRedoAction defines model for NoArgumentRedoAction.
type NoArgumentRedoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRepairAction defines model for NoArgumentRepairAction.
type NoArgumentRepairAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentResetAction defines model for NoArgumentResetAction.
type NoArgumentResetAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentSolveAction defines model for NoArgumentSolveAction.
type NoArgumentSolveAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentUndoAction defines model for NoArgumentUndoAction.
type NoArgumentUndoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// PuzzleSource defines model for PuzzleSource.
type PuzzleSource struct {
	Kind string `json:"kind"`

	// Puzzle An 81-cell puzzle; dot or zero represents an empty cell.
	Puzzle string `json:"puzzle"`
}

// RedoAction defines model for RedoAction.
type RedoAction = NoArgumentRedoAction

// RepairAction defines model for RepairAction.
type RepairAction = NoArgumentRepairAction

// ResetAction defines model for ResetAction.
type ResetAction = NoArgumentResetAction

// Revision defines model for Revision.
type Revision = int64

// RevisionConflict defines model for RevisionConflict.
type RevisionConflict struct {
	CurrentRevision Revision `json:"current_revision"`
	Error           struct {
		Cell    *CellPosition `json:"cell,omitempty"`
		Code    string        `json:"code"`
		Field   *string       `json:"field,omitempty"`
		Message string        `json:"message"`
	} `json:"error"`
	Snapshot Snapshot `json:"snapshot"`
}

// Session defines model for Session.
type Session struct {
	Id       SessionId `json:"id"`
	Revision Revision  `json:"revision"`
	Snapshot Snapshot  `json:"snapshot"`
}

// SessionId defines model for SessionId.
type SessionId = string

// SessionList defines model for SessionList.
type SessionList struct {
	Sessions []SessionSummary `json:"sessions"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Id SessionId `json:"id"`

	// Recovered True when the summary was discovered from durable recovery at startup.
	Recovered bool       `json:"recovered"`
	Revision  Revision   `json:"revision"`
	Status    GameStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// SetValueAction defines model for SetValueAction.
type SetValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CanRedo    bool         `json:"can_redo"`
	CanUndo    bool         `json:"can_undo"`
	Candidates DigitSetGrid `json:"candidates"`
	Givens     ValueGrid    `json:"givens"`
	Invalid    BooleanGrid  `json:"invalid"`
	Notes      DigitSetGrid `json:"notes"`
	Status     GameStatus   `json:"status"`
	Values     ValueGrid    `json:"values"`
}

// SolveAction defines model for SolveAction.
type SolveAction = NoArgumentSolveAction

// ToggleNoteAction defines model for ToggleNoteAction.
type ToggleNoteAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// UndoAction defines model for UndoAction.
type UndoAction = NoArgumentUndoAction

// ValueGrid defines model for ValueGrid.
type ValueGrid = []ValueRow

// ValueRow defines model for ValueRow.
type ValueRow = []CellValue

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// ImportSessionApplicationVndSudokuSessionPlusJSONBody defines parameters for ImportSession.
type ImportSessionApplicationVndSudokuSessionPlusJSONBody = openapi_types.File

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody defines body for ImportSession for application/vnd.sudoku.session+json ContentType.
type ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody = ImportSessionApplicationVndSudokuSessionPlusJSONBody

// ApplyActionJSONRequestBody defines body for ApplyAction for application/json ContentType.
type ApplyActionJSONRequestBody = ActionRequest

// AsSetValueAction returns the union data inside the ActionRequest as a SetValueAction
func (t ActionRequest) AsSetValueAction() (SetValueAction, error) {
	var body SetValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetValueAction overwrites any union data inside the ActionRequest as the provided SetValueAction
func (t *ActionRequest) FromSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetValueAction performs a merge with any union data inside the ActionRequest, using the provided SetValueAction
func (t *ActionRequest) MergeSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClearValueAction returns the union data inside the ActionRequest as a ClearValueAction
func (t ActionRequest) AsClearValueAction() (ClearValueAction, error) {
	var body ClearValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClearValueAction overwrites any union data inside the ActionRequest as the provided ClearValueAction
func (t *ActionRequest) FromClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClearValueAction performs a merge with any union data inside the ActionRequest, using the provided ClearValueAction
func (t *ActionRequest) MergeClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResetAction returns the union data inside the ActionRequest as a ResetAction
func (t ActionRequest) AsResetAction() (ResetAction, error) {
	var body ResetAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResetAction overwrites any union data inside the ActionRequest as the provided ResetAction
func (t *ActionRequest) FromResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResetAction performs a merge with any union data inside the ActionRequest, using the provided ResetAction
func (t *ActionRequest) MergeResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUndoAction returns the union data inside the ActionRequest as a UndoAction
func (t ActionRequest) AsUndoAction() (UndoAction, error) {
	var body UndoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUndoAction overwrites any union data inside the ActionRequest as the provided UndoAction
func (t *ActionRequest) FromUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUndoAction performs a merge with any union data inside the ActionRequest, using the provided UndoAction
func (t *ActionRequest) MergeUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRedoAction returns the union data inside the ActionRequest as a RedoAction
func (t ActionRequest) AsRedoAction() (RedoAction, error) {
	var body RedoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRedoAction overwrites any union data inside the ActionRequest as the provided RedoAction
func (t *ActionRequest) FromRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRedoAction performs a merge with any union data inside the ActionRequest, using the provided RedoAction
func (t *ActionRequest) MergeRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyHintAction returns the union data inside the ActionRequest as a ApplyHintAction
func (t ActionRequest) AsApplyHintAction() (ApplyHintAction, error) {
	var body ApplyHintAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyHintAction overwrites any union data inside the ActionRequest as the provided ApplyHintAction
func (t *ActionRequest) FromApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyHintAction performs a merge with any union data inside the ActionRequest, using the provided ApplyHintAction
func (t *ActionRequest) MergeApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToggleNoteAction returns the union data inside the ActionRequest as a ToggleNoteAction
func (t ActionRequest) AsToggleNoteAction() (ToggleNoteAction, error) {
	var body ToggleNoteAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToggleNoteAction overwrites any union data inside the ActionRequest as the provided ToggleNoteAction
func (t *ActionRequest) FromToggleNoteAction(v ToggleNoteAction) error {
	v.Kind = "toggle-note"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToggleNoteAction performs a merge with any union data inside the ActionRequest, using the provided ToggleNoteAction
func (t *ActionRequest) MergeToggleNoteAction(v ToggleNoteAction) error {
	v.Kind = "toggle-note"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClearNotesAction returns the union data inside the ActionRequest as a ClearNotesAction
func (t ActionRequest) AsClearNotesAction() (ClearNotesAction, error) {
	var body ClearNotesAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClearNotesAction overwrites any union data inside the ActionRequest as the provided ClearNotesAction
func (t *ActionRequest) FromClearNotesAction(v ClearNotesAction) error {
	v.Kind = "clear-notes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClearNotesAction performs a merge with any union data inside the ActionRequest, using the provided ClearNotesAction
func (t *ActionRequest) MergeClearNotesAction(v ClearNotesAction) error {
	v.Kind = "clear-notes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRepairAction returns the union data inside the ActionRequest as a RepairAction
func (t ActionRequest) AsRepairAction() (RepairAction, error) {
	var body RepairAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRepairAction overwrites any union data inside the ActionRequest as the provided RepairAction
func (t *ActionRequest) FromRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRepairAction performs a merge with any union data inside the ActionRequest, using the provided RepairAction
func (t *ActionRequest) MergeRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolveAction returns the union data inside the ActionRequest as a SolveAction
func (t ActionRequest) AsSolveAction() (SolveAction, error) {
	var body SolveAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolveAction overwrites any union data inside the ActionRequest as the provided SolveAction
func (t *ActionRequest) FromSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolveAction performs a merge with any union data inside the ActionRequest, using the provided SolveAction
func (t *ActionRequest) MergeSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ActionRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "apply-hint":
		return t.AsApplyHintAction()
	case "clear-notes":
		return t.AsClearNotesAction()
	case "clear-value":
		return t.AsClearValueAction()
	case "redo":
		return t.AsRedoAction()
	case "repair":
		return t.AsRepairAction()
	case "reset":
		return t.AsResetAction()
	case "set-value":
		return t.AsSetValueAction()
	case "solve":
		return t.AsSolveAction()
	case "toggle-note":
		return t.AsToggleNoteAction()
	case "undo":
		return t.AsUndoAction()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ActionRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDifficultySource returns the union data inside the CreateSessionRequest_Source as a DifficultySource
func (t CreateSessionRequest_Source) AsDifficultySource() (DifficultySource, error) {
	var body DifficultySource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDifficultySource overwrites any union data inside the CreateSessionRequest_Source as the provided DifficultySource
func (t *CreateSessionRequest_Source) FromDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDifficultySource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided DifficultySource
func (t *CreateSessionRequest_Source) MergeDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPuzzleSource returns the union data inside the CreateSessionRequest_Source as a PuzzleSource
func (t CreateSessionRequest_Source) AsPuzzleSource() (PuzzleSource, error) {
	var body PuzzleSource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPuzzleSource overwrites any union data inside the CreateSessionRequest_Source as the provided PuzzleSource
func (t *CreateSessionRequest_Source) FromPuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePuzzleSource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided PuzzleSource
func (t *CreateSessionRequest_Source) MergePuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateSessionRequest_Source) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateSessionRequest_Source) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "difficulty":
		return t.AsDifficultySource()
	case "puzzle":
		return t.AsPuzzleSource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateSessionRequest_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateSessionRequest_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(w http.ResponseWriter, r *http.Request)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportSession operation middleware
func (siw *ServerInterfaceWrapper) ImportSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyAction(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportSession operation middleware
func (siw *ServerInterfaceWrapper) ExportSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewHint operation middleware
func (siw *ServerInterfaceWrapper) PreviewHint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewHint(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions", wrapper.ListSessions)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions", wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/import", wrapper.ImportSession)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/{sessionId}/actions", wrapper.ApplyAction)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/export", wrapper.ExportSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/hint", wrapper.PreviewHint)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type PayloadTooLargeJSONResponse Error

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedJSONResponse struct {
	Body Error

	Headers UnauthorizedResponseHeaders
}

type UnprocessableEntityJSONResponse Error

type UnsupportedMediaTypeJSONResponse Error

type ListSessionsRequestObject struct {
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse SessionList

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessions401JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListSessions500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListSessions500JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201ResponseHeaders struct {
	Location string
}

type CreateSession201JSONResponse struct {
	Body    Session
	Headers CreateSession201ResponseHeaders
}

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSession401JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response CreateSession413JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateSession415JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateSession422JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportSessionRequestObject struct {
	Body *ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
}

type ImportSessionResponseObject interface {
	VisitImportSessionResponse(w http.ResponseWriter) error
}

type ImportSession201ResponseHeaders struct {
	Location string
}

type ImportSession201JSONResponse struct {
	Body    Session
	Headers ImportSession201ResponseHeaders
}

func (response ImportSession201JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportSession400JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportSession401JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ImportSession413JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ImportSession415JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ImportSession422JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportSession500JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSession401JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteSession404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSession404JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSession500JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse Session

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSession401JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSession404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSession404JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSession500JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyActionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
	Body      *ApplyActionJSONRequestBody
}

type ApplyActionResponseObject interface {
	VisitApplyActionResponse(w http.ResponseWriter) error
}

type ApplyAction200JSONResponse ActionResponse

func (response ApplyAction200JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction400JSONResponse struct{ BadRequestJSONResponse }

func (response ApplyAction400JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ApplyAction401JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ApplyAction404JSONResponse struct{ NotFoundJSONResponse }

func (response ApplyAction404JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction409JSONResponse RevisionConflict

func (response ApplyAction409JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ApplyAction413JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ApplyAction415JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ApplyAction422JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction500JSONResponse struct{ InternalErrorJSONResponse }

func (response ApplyAction500JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type ExportSessionResponseObject interface {
	VisitExportSessionResponse(w http.ResponseWriter) error
}

type ExportSession200ResponseHeaders struct {
	ContentDisposition string
}

type ExportSession200ApplicationVndSudokuSessionPlusJSONResponse struct {
	Body    openapi_types.File
	Headers ExportSession200ResponseHeaders
}

func (response ExportSession200ApplicationVndSudokuSessionPlusJSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.sudoku.session+json")
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportSession401JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession404JSONResponse struct{ NotFoundJSONResponse }

func (response ExportSession404JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportSession500JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHintRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type PreviewHintResponseObject interface {
	VisitPreviewHintResponse(w http.ResponseWriter) error
}

type PreviewHint200JSONResponse HintPreview

func (response PreviewHint200JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PreviewHint401JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type PreviewHint404JSONResponse struct{ NotFoundJSONResponse }

func (response PreviewHint404JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response PreviewHint422JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint500JSONResponse struct{ InternalErrorJSONResponse }

func (response PreviewHint500JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth400JSONResponse struct{ BadRequestJSONResponse }

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetHealth500JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(ctx context.Context, request ImportSessionRequestObject) (ImportSessionResponseObject, error)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(ctx context.Context, request ApplyActionRequestObject) (ApplyActionResponseObject, error)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(ctx context.Context, request ExportSessionRequestObject) (ExportSessionResponseObject, error)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(ctx context.Context, request PreviewHintRequestObject) (PreviewHintResponseObject, error)
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request) {
	var request ListSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportSession operation middleware
func (sh *strictHandler) ImportSession(w http.ResponseWriter, r *http.Request) {
	var request ImportSessionRequestObject

	var body ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportSession(ctx, request.(ImportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportSessionResponseObject); ok {
		if err := validResponse.VisitImportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request DeleteSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request GetSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyAction operation middleware
func (sh *strictHandler) ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ApplyActionRequestObject

	request.SessionId = sessionId

	var body ApplyActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyAction(ctx, request.(ApplyActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyActionResponseObject); ok {
		if err := validResponse.VisitApplyActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportSession operation middleware
func (sh *strictHandler) ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ExportSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportSession(ctx, request.(ExportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportSessionResponseObject); ok {
		if err := validResponse.VisitExportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewHint operation middleware
func (sh *strictHandler) PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request PreviewHintRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewHint(ctx, request.(PreviewHintRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewHint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewHintResponseObject); ok {
		if err := validResponse.VisitPreviewHintResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8aXPbtrZ/BcPXb5eiJcdJHHfeBzfJTTI3TfNit525sV8GIo8k3IAAC4C2FY/++xss",
	"BMFFFumladKXL7EkLGfHWXBwHaU8LzgDpmR0dB0VWOAcFAjz6QSkJJy9yfSHDGQqSKEIZ9FR9EuB/ygB",
	"CcwyniNpByKSAVNkQUAk6I1CRCLGFcIoFWB+wTSJ4ojoBQqsVlEcMZxDdBRJv1McCfijJAKy6EiJEuJI",
	"pivIsQbhBwGL6Cj6r70a6D37q9yrYd1sNnoRWXAmweDxE84+wB8lSKU/pZwpYOZPXBSUpFjjtPcfqRG7",
	"juAK5wUF86cQXNgpmYaSsAtMSTYRbrE4WhCgmYaflyKFKI5ykBIvwX+F8lIqJIFCqhBc4VTRNeIMkCyL",
	"ggsFGfpMmAZ6KKIvDVAGySZLTleAHGSa8jmmCy5yyBAX6IJwihVIpFaAlMBM6s2RJoXAqUqiTRy9YQoE",
	"w/RljfXtCWWXmtgfQrKoAMqUlzQzIjIHpFGloOBeaHHMUMngqoBUWQJkpcBzQolaowUmtBSAeJqWQkCG",
	"Lola8VIhCvgzYUtUQS8NWd5x9U9esuxuFHECPmFcTRZmuYasOP25xFZj7Ij7lQnIvJpmHOw+cEWkZf57",
	"vKYcZ6ecv8ViCXdDtrCLTRTnE2qWC5GtuD/n2RrBVQqQWbnM8RXJyxxJ8gXuWyHCfVLOFmRZatYbGCjJ",
	"iaXCrwyXasUF+QJ35HcZrhRiPwcsQCD9q7aIdkWtr97s3Yf4+9WQ26+2wMY2ECm1pHOBnE3TdnkFOHOW",
	"//fff58c1yAaFGuYUs60KY1+MmtHcaTWhRFjJQhbaoAMLQvBU433nMJLpohaDyepAQLYkjD4AP+B1OJ1",
	"HV1gWrboDZTadWmZs+joURwJfhkdzTaxt0Z5XioNxcQMDrmRYqb1IF1htgSEUSH4nEKOzECDhqOPO162",
	"wNA8HpyatTRcEEy1NHgtNIMt+7VJMpy//2PgEihF7iCYlwo5jOeADPkhc4Lvz6OfISP41DD0bgrgV5zk",
	"esmJEZJtR8Fzu9FEb1z5DX6B+zYGN26G5mukVkQiXoAw6CbB/kYwj408/ovYQwFYmUdHHyMJamJlI45S",
	"Clj4TwIkaG+hZBk3H81/mqDryYow/ZPiyyUFfTzU0/UHacYXmGg1k5xeQHTe0bfYQRQ4ORnRyOeEYWXZ",
	"kuOi0IMdJ93GW6h4rEe8JkzZdVsQbZn0XA95p0e0ZjmFuWHWb3qEn2Xos2X4B8h4MNAQZutQ/WswWDNh",
	"61gJNbI1J7c6m6oJsuXMttH6Rz805PSWCadmiCaln2VEZ8vwX5mnySaOCqEFV63fWc/aepdxxBn8soiO",
	"Pu7yohuIbeKbh3eYt2tCSOddYxto7Vp28NC2aO8a3+HFIJqEarAb+EBOdw0OZWlzHmi+DXeMemcZ0d9h",
	"+t6KAtE6u8BUgpcOYk9YAbKkapdN9VvosSa2uiDVYXgzYm6ctp4MF3LFd+51Uo3bxNElFoywpexGn+84",
	"myywwhRlBC8Zl4qkUh/eWZlChvBCgTCu3hLngLCB3zjXOE2hUGDcHaIgN2t3rKn7AguB15GNJquQ9GON",
	"fYBUXFGyts18rt2W0DZXpB7BH+wdn938+ZdT9BSzT9aCeszmnFPArPrV2pLeX40fZLb21LlR1oHS52aO",
	"np3jqzd21uGsTcQ4sufNzetpvTTSorAqd+7+CudwYke2mYT9CeQw8msGJAho1cu3lqUYx7oq+Px0G235",
	"THy8aRztpqvQcrabmHf3dcv1ofiTZf0rQbLBPHdzPvDLJs+fxVFOWP2hzf9gXrhVVwiHLxmI30i90gZi",
	"iHCbs01vNYcFFzBqShWRaN/LBLYVQvbvWkUIU7AEEdXRxicPYJc81ZAaou4Y46d9GoTlC7Ik6gRUPW0Y",
	"quE8YXk6FM22QeWXkaeWp3TsmNRBuE2kFthN5PuEXjPpPZfkFkp9G5beI3G2YfNbFZE2T8l/g+BIQKE9",
	"X6YkwgxBXqi1iW71CdgL07QPiY5T8/B0u1cD2gyoOgf+3Xi01eTGA9jX9qC/ScJWge5fibACsAKXtgkC",
	"4xHEdUn9HdF0RhYLkpZUrbebymrESVUmKMovX+jW+O+9+dUNvmtI19l9V4jR3P28zRRHlT6avwhIUedF",
	"AMu1yftkpMyjOFphoTmomSu0PwMXhPYmNTqQj2Nf1oBmGIn6RDxYZ5fz5YQzmNFPpiVR43TWn7ZDvTS7",
	"R9ubajhQcVQy8kcJ7mclSgh2GuUTVpNGO4XhxLGbjdvJV7XG+PDVnJ0ZxxegMKFdA2YW6JMBM+u5SZXW",
	"mtKtL1bfmIRrvD2p2ldxaZUgFlzMSZYBm3BBlsTmubpFqcrUTlLOFpSkIRR1Yrv6xsdZ1Rcuw95Jueuj",
	"1+yDKeWXBiDGJy4MY3zicqKMV1FOAUISqYClMHHp8bhdV+wzGiE7Rp6lrpKwy8H3vqOvMAwQEMPqjS8Y",
	"G91/C2ypVtHRbDo1wus/96Dls+btmbumtiTSAFwv1yeaQVjdkM1JIfhSgJQ1u6vMZ9bLiteAqQZq3KHr",
	"d67s78oss9v4upl9KL12uYeHdvUBu8LIOB6N9pPiSEG6Mtb7FrLkC1gDDpCbYzXv93loPBG2seG9NjBw",
	"OZIbY5JH493a7Rk+s28fKu/4sViWOTD1N0gT1cgGifaviKc7LB4IwyAb/1VxdEW/B8KyrsN8VSRtYfRB",
	"cAxLJV8RR1safCAcgxrZV0TRuXH3iGEjBh2HWRs4F2r3nINVEH7dvTx2ODOOK7JDfkQZV4gL9GVARq06",
	"eQ9njYNYfyyw0v5rdBT978fp5Flyfn042/wwNKp04PaR63s1y9+zMf5+TfCHAKwFFzlW1nd9chDtyjNX",
	"U59XwedIp70UApi6FWF8sI8pHZBWa4T98XUnesigSeVuVN2leIuS57eqm/emIOIuaYK1+5gYXHgbwQCb",
	"Mxp4T/vPuknQoggJ0xwDyWCvwNeXEz9G+cnBwfznp1fvnhX/k+7/pt4+uXxxeKzXCM6AJweNM2B/v3kG",
	"HE/+jSdfppNnnybn//ih74hy278l45PXdubwWr7b6qTMcyzWzeSajWFvvBbh97uBitXaDyxTKb8AAT1N",
	"C6eiBHS5AmbuhkgLjbkXkhHpZqGF4Lm9Lk4BucXWCCskFRaqLJKaT0HF9VaSPPqWQxyVRYa1HcaqYV31",
	"lxNF8t2OZkf6q2sRwcohEfvZqb7hklV4T/PuiZg7JFOGlreqTXpZEVjDMUy4yyUhzDKiZWVwpt7UEjZx",
	"tCQXwHbOMqJVTakSjcMupVSz3D3VcdDdRh0NY8Zg1BIBRxG/UJhZrarVAb1vcYvp+42COzczvzE71Lzy",
	"/c1bou81FVEr71BPyswYXQr1s8ZcvvSXzYbuo+0cpKUgan2i17EssE1Cx6Wt1thP/6x8C25aPSeKfwZN",
	"qKZL9aHqM9JuFVy4a7cShP6TyLDXasEbbU+Qmdu4UmqHyuBUt0fVHFwpVVSNOAve49KtAJ2UGf9coten",
	"p+/R8fs3CK4KLl2vo+lwI2xpbwLbjiKkOKI8xRQpzqlEmGVnTEKBBVZA1yiDgvI1ZCilRFM8QacNnFxZ",
	"VWFFLsCgpa0yxGeskicZB909sd7Ae5LJGTtjwXrUFDkl4gxRzos5Tj+juYZhgUuqEvSL6ULhQqODVU1P",
	"hM8Y42ziJ9mFQNiOU0wlDwb3dp0l6LlF8IzJlWnFlMAyhHt6xkLuEuEolANTVaOZRgCSMy0glKTgrqLX",
	"/cDRUfTzm9O64Vd/0LJYRQTRcYOojqWGaVVkgTT9DJe1eBBl7s+0eK8tFAhrRKJZMk2m5qJMAQwXJDqK",
	"HiWzZGbq5WplJH8PF2TvYrYXhktLe8+iLeiqFEyiOS9ZBpmLHggY8UGWOMKNqTq8XFXeSLjvJtKhZKQD",
	"upNqy1a38v50OqD1alRXtIkfe5qi3M8BMlxkJgqar1HOpWZvCkzRNXLhAVoQ4VpGD6azbdt7fPYaHZWb",
	"OHpskbt5UrMTedOQE42KudF/AaFe1X115oIfXpog3ZP4fBNHBbdBdJMTjXtirvscpPqJZ2PbFefr5v2n",
	"GuZXWi+xAsQF0gJh8sZYrpHPTfuzO7xzFtwrc3eo7GkX/mSYOl+/96nsetcTHa/acBab9jZKILtxS7e8",
	"H+JvqSXJo2Q/eZIkz/Rfj5NkliSzw+TJQZIkyeEs2X+WJE8T++8wSZ48TQ739d/7T5Jnj81X+8kjM/tx",
	"MtN/jWp17L3Kt2ke6u72UkuRZvetSNs6C8MG7tSAmyGstceeB6Zw0GqxfcstIH2mhlor+OuHt4gvzDnG",
	"4LLaxJ+X2L7Y4PNJbVu2tzPBZLA5GKKSwRMKt1X9g9mj3ZPafehm3uMhm/U0sOrJ+/tDJndble/DVlnB",
	"1drnxMMpY62/2iLUBaqu1drEnRNqj+QaT8N7Z9Ha4iMV1ycy9oeVOxMbTwCkpoBofZtGSz4xnpP2iJpD",
	"EVES6OJHI4/az7KHnm2p0rut9IGxIBTkWirIkT5krUvQNLlvDAJjTe4FyxJpTvvEQfaPrgq7uUEPc1fn",
	"4zptNidMcypu3qA5OHz89EmPrvyF7I2VgYCf2vA4l1ObHpahHGdQ5THvZHrae/2//flW7I9VNGN//OsD",
	"oUs93OZc+wd6NlZoKNhHIZqa/cJ8H2p2Qz0O+uO3Soa11HJG19rQ1Jl3/YfI0CUIQHbf7Pbu54GF4eZJ",
	"/sWX++DBCyJTLLLgENBo9mC4zW110UiT0K9AbaXy9M8yQq6k6BHz3o7GMAOF05W2Gi5D/S0x7QPgzNi+",
	"ZqhfIWrC/YBfr3AOBcVrG2YET2htqSHXQ8LS1fkOxduzl60773SN2yTe4jWcmmSJezDJc7IQ/IJkOi4s",
	"FMmJVCRFKWeW8+naPiDFaYJeakk+Y1V/NcpL5V62YamA3NyWse99uJXrt7BSSJB95MWeXGdMKkyrtm2J",
	"KGBNe2VcKRYAVzLb3Zv1ORnmWmbw+MNtozrpal2Nl1+q3PGsNyU89YFaWGqyr9L4uOtAS1xVZKmflOmu",
	"9sivZkaPiJuaj4IMcmDuz3a03iXYYkJ6WvOt9TB+yxpVXQCVyf+TPIWxBudg+uzeCNe5ArOFdF1lJRIZ",
	"zUn+nt6O0Xjztp72MrPw7Yd+W73L3sJVFWjdmBHUZi3oVqnjJVxnC+drBTJ2ryGaOMkERx2r9fKqHRoN",
	"Vs+/QnzUldIbIs9mTFK9yfSCyCJozm7lK8vl0j5ll/FLZlJpOt5kOIdmVOIfpoqw0n6I3vBHP/a/zyJL",
	"qaqjKdGIn0VbA5RvwmmxsmPEMaR6+92xrenRB/NbquaNXk/W9YO8tk0LD3Ycha0nvQ/maSBNLUcFnm1l",
	"WqssSW1oa9/jTzxlvqZ1dcTT5ktTqnoz0/p5bOnKfm0Ju0fP2LaBfdkqSK9AuYazW4lR8JRddRHEd54N",
	"9rgcAFtsoWOMFh+38m29mtty01V+o6OP54085QrSzx68VUXFiokOq/NNa43rTdwsHX881/GFLWxaHjeJ",
	"8MIWNetCZ11HjOKoFNQVfI/29mb7T5NpMk1mR4fTw6mJWxw47UWdDzNZCIAuDq7cWDEm7oDkLvo1A71G",
	"3bFexdvL7jonPgbGmS0J6jUmruBcRW5+Ja8Xm/PN/wUAAP//ZwRwooRZAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
