//go:build go1.22

// Package webapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ActionKind.
const (
	ApplyHint  ActionKind = "apply-hint"
	ClearValue ActionKind = "clear-value"
	Redo       ActionKind = "redo"
	Repair     ActionKind = "repair"
	Reset      ActionKind = "reset"
	SetNotes   ActionKind = "set-notes"
	SetValue   ActionKind = "set-value"
	Solve      ActionKind = "solve"
	Undo       ActionKind = "undo"
)

// Defines values for Difficulty.
const (
	Easy   Difficulty = "easy"
	Evil   Difficulty = "evil"
	Expert Difficulty = "expert"
	Hard   Difficulty = "hard"
	Medium Difficulty = "medium"
)

// Defines values for ErrorCode.
const (
	ErrorCodeForbiddenOrigin      ErrorCode = "forbidden-origin"
	ErrorCodeImmutableCell        ErrorCode = "immutable-cell"
	ErrorCodeInternalError        ErrorCode = "internal-error"
	ErrorCodeInvalidAction        ErrorCode = "invalid-action"
	ErrorCodeInvalidCell          ErrorCode = "invalid-cell"
	ErrorCodeInvalidJson          ErrorCode = "invalid-json"
	ErrorCodeInvalidRequest       ErrorCode = "invalid-request"
	ErrorCodeInvalidSession       ErrorCode = "invalid-session"
	ErrorCodeNoHint               ErrorCode = "no-hint"
	ErrorCodeNoRedo               ErrorCode = "no-redo"
	ErrorCodeNoUndo               ErrorCode = "no-undo"
	ErrorCodeNoteNotAllowed       ErrorCode = "note-not-allowed"
	ErrorCodePayloadTooLarge      ErrorCode = "payload-too-large"
	ErrorCodePersistenceFailed    ErrorCode = "persistence-failed"
	ErrorCodeRevisionConflict     ErrorCode = "revision-conflict"
	ErrorCodeSessionNotFound      ErrorCode = "session-not-found"
	ErrorCodeUnauthorized         ErrorCode = "unauthorized"
	ErrorCodeUnsupportedMediaType ErrorCode = "unsupported-media-type"
)

// Defines values for GameStatus.
const (
	InProgress GameStatus = "in-progress"
	Invalid    GameStatus = "invalid"
	Solved     GameStatus = "solved"
)

// ActionKind defines model for ActionKind.
type ActionKind string

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	union json.RawMessage
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	Result   ActionResult `json:"result"`
	Revision Revision     `json:"revision"`
	Snapshot Snapshot     `json:"snapshot"`

	// Warnings Non-fatal diagnostics produced after the game action was accepted.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ActionResult defines model for ActionResult.
type ActionResult struct {
	Action  ActionKind   `json:"action"`
	CanRedo bool         `json:"can_redo"`
	CanUndo bool         `json:"can_undo"`
	Changes []CellChange `json:"changes"`
	Hint    *Hint        `json:"hint,omitempty"`
	Status  GameStatus   `json:"status"`
}

// AdoptCandidatesAsNotesAction defines model for AdoptCandidatesAsNotesAction.
type AdoptCandidatesAsNotesAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// ApplyHintAction defines model for ApplyHintAction.
type ApplyHintAction = NoArgumentApplyHintAction

// BooleanGrid defines model for BooleanGrid.
type BooleanGrid = []BooleanRow

// BooleanRow defines model for BooleanRow.
type BooleanRow = []bool

// CellChange defines model for CellChange.
type CellChange struct {
	// After Zero represents an empty cell.
	After CellValue `json:"after"`

	// Before Zero represents an empty cell.
	Before        CellValue `json:"before"`
	Column        int       `json:"column"`
	InvalidAfter  bool      `json:"invalid_after"`
	InvalidBefore bool      `json:"invalid_before"`
	NotesAfter    DigitSet  `json:"notes_after"`
	NotesBefore   DigitSet  `json:"notes_before"`
	Row           int       `json:"row"`
}

// CellPosition defines model for CellPosition.
type CellPosition struct {
	Column int `json:"column"`
	Row    int `json:"row"`
}

// CellValue Zero represents an empty cell.
type CellValue = int

// ClearValueAction defines model for ClearValueAction.
type ClearValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Source CreateSessionRequest_Source `json:"source"`
}

// CreateSessionRequest_Source defines model for CreateSessionRequest.Source.
type CreateSessionRequest_Source struct {
	union json.RawMessage
}

// Difficulty defines model for Difficulty.
type Difficulty string

// DifficultySource defines model for DifficultySource.
type DifficultySource struct {
	Difficulty Difficulty `json:"difficulty"`
	Kind       string     `json:"kind"`
}

// Digit defines model for Digit.
type Digit = int

// DigitSet defines model for DigitSet.
type DigitSet = []Digit

// DigitSetGrid defines model for DigitSetGrid.
type DigitSetGrid = []DigitSetRow

// DigitSetRow defines model for DigitSetRow.
type DigitSetRow = []DigitSet

// Error defines model for Error.
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Cell    *CellPosition `json:"cell,omitempty"`
	Code    ErrorCode     `json:"code"`
	Field   *string       `json:"field,omitempty"`
	Message string        `json:"message"`
}

// GameStatus defines model for GameStatus.
type GameStatus string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Hint defines model for Hint.
type Hint struct {
	Column    int    `json:"column"`
	Reason    string `json:"reason"`
	Row       int    `json:"row"`
	Technique string `json:"technique"`
	Value     Digit  `json:"value"`
}

// HintPreview defines model for HintPreview.
type HintPreview struct {
	Hint     Hint     `json:"hint"`
	Revision Revision `json:"revision"`
}

// NoArgumentApplyHintAction defines model for NoArgumentApplyHintAction.
type NoArgumentApplyHintAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRedoAction defines model for NoArgumentRedoAction.
type NoArgumentRedoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRepairAction defines model for NoArgumentRepairAction.
type NoArgumentRepairAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentResetAction defines model for NoArgumentResetAction.
type NoArgumentResetAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentSolveAction defines model for NoArgumentSolveAction.
type NoArgumentSolveAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentUndoAction defines model for NoArgumentUndoAction.
type NoArgumentUndoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// PuzzleSource defines model for PuzzleSource.
type PuzzleSource struct {
	Kind string `json:"kind"`

	// Puzzle An 81-cell puzzle; dot or zero represents an empty cell.
	Puzzle string `json:"puzzle"`
}

// RedoAction defines model for RedoAction.
type RedoAction = NoArgumentRedoAction

// RepairAction defines model for RepairAction.
type RepairAction = NoArgumentRepairAction

// ResetAction defines model for ResetAction.
type ResetAction = NoArgumentResetAction

// Revision defines model for Revision.
type Revision = int64

// RevisionConflict defines model for RevisionConflict.
type RevisionConflict struct {
	CurrentRevision Revision `json:"current_revision"`
	Error           struct {
		Cell    *CellPosition `json:"cell,omitempty"`
		Code    string        `json:"code"`
		Field   *string       `json:"field,omitempty"`
		Message string        `json:"message"`
	} `json:"error"`
	Snapshot Snapshot `json:"snapshot"`
}

// Session defines model for Session.
type Session struct {
	Id       SessionId `json:"id"`
	Revision Revision  `json:"revision"`
	Snapshot Snapshot  `json:"snapshot"`
}

// SessionId defines model for SessionId.
type SessionId = string

// SessionList defines model for SessionList.
type SessionList struct {
	Sessions []SessionSummary `json:"sessions"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Id SessionId `json:"id"`

	// Recovered True when the summary was discovered from durable recovery at startup.
	Recovered bool       `json:"recovered"`
	Revision  Revision   `json:"revision"`
	Status    GameStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// SetNotesAction defines model for SetNotesAction.
type SetNotesAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Values           DigitSet `json:"values"`
}

// SetValueAction defines model for SetValueAction.
type SetValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CanRedo    bool         `json:"can_redo"`
	CanUndo    bool         `json:"can_undo"`
	Candidates DigitSetGrid `json:"candidates"`
	Givens     ValueGrid    `json:"givens"`
	Invalid    BooleanGrid  `json:"invalid"`
	Notes      DigitSetGrid `json:"notes"`
	Status     GameStatus   `json:"status"`
	Values     ValueGrid    `json:"values"`
}

// SolveAction defines model for SolveAction.
type SolveAction = NoArgumentSolveAction

// UndoAction defines model for UndoAction.
type UndoAction = NoArgumentUndoAction

// ValueGrid defines model for ValueGrid.
type ValueGrid = []ValueRow

// ValueRow defines model for ValueRow.
type ValueRow = []CellValue

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// ImportSessionApplicationVndSudokuSessionPlusJSONBody defines parameters for ImportSession.
type ImportSessionApplicationVndSudokuSessionPlusJSONBody = openapi_types.File

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody defines body for ImportSession for application/vnd.sudoku.session+json ContentType.
type ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody = ImportSessionApplicationVndSudokuSessionPlusJSONBody

// ApplyActionJSONRequestBody defines body for ApplyAction for application/json ContentType.
type ApplyActionJSONRequestBody = ActionRequest

// AsSetValueAction returns the union data inside the ActionRequest as a SetValueAction
func (t ActionRequest) AsSetValueAction() (SetValueAction, error) {
	var body SetValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetValueAction overwrites any union data inside the ActionRequest as the provided SetValueAction
func (t *ActionRequest) FromSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetValueAction performs a merge with any union data inside the ActionRequest, using the provided SetValueAction
func (t *ActionRequest) MergeSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClearValueAction returns the union data inside the ActionRequest as a ClearValueAction
func (t ActionRequest) AsClearValueAction() (ClearValueAction, error) {
	var body ClearValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClearValueAction overwrites any union data inside the ActionRequest as the provided ClearValueAction
func (t *ActionRequest) FromClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClearValueAction performs a merge with any union data inside the ActionRequest, using the provided ClearValueAction
func (t *ActionRequest) MergeClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResetAction returns the union data inside the ActionRequest as a ResetAction
func (t ActionRequest) AsResetAction() (ResetAction, error) {
	var body ResetAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResetAction overwrites any union data inside the ActionRequest as the provided ResetAction
func (t *ActionRequest) FromResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResetAction performs a merge with any union data inside the ActionRequest, using the provided ResetAction
func (t *ActionRequest) MergeResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUndoAction returns the union data inside the ActionRequest as a UndoAction
func (t ActionRequest) AsUndoAction() (UndoAction, error) {
	var body UndoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUndoAction overwrites any union data inside the ActionRequest as the provided UndoAction
func (t *ActionRequest) FromUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUndoAction performs a merge with any union data inside the ActionRequest, using the provided UndoAction
func (t *ActionRequest) MergeUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRedoAction returns the union data inside the ActionRequest as a RedoAction
func (t ActionRequest) AsRedoAction() (RedoAction, error) {
	var body RedoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRedoAction overwrites any union data inside the ActionRequest as the provided RedoAction
func (t *ActionRequest) FromRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRedoAction performs a merge with any union data inside the ActionRequest, using the provided RedoAction
func (t *ActionRequest) MergeRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyHintAction returns the union data inside the ActionRequest as a ApplyHintAction
func (t ActionRequest) AsApplyHintAction() (ApplyHintAction, error) {
	var body ApplyHintAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyHintAction overwrites any union data inside the ActionRequest as the provided ApplyHintAction
func (t *ActionRequest) FromApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyHintAction performs a merge with any union data inside the ActionRequest, using the provided ApplyHintAction
func (t *ActionRequest) MergeApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetNotesAction returns the union data inside the ActionRequest as a SetNotesAction
func (t ActionRequest) AsSetNotesAction() (SetNotesAction, error) {
	var body SetNotesAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetNotesAction overwrites any union data inside the ActionRequest as the provided SetNotesAction
func (t *ActionRequest) FromSetNotesAction(v SetNotesAction) error {
	v.Kind = "set-notes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetNotesAction performs a merge with any union data inside the ActionRequest, using the provided SetNotesAction
func (t *ActionRequest) MergeSetNotesAction(v SetNotesAction) error {
	v.Kind = "set-notes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdoptCandidatesAsNotesAction returns the union data inside the ActionRequest as a AdoptCandidatesAsNotesAction
func (t ActionRequest) AsAdoptCandidatesAsNotesAction() (AdoptCandidatesAsNotesAction, error) {
	var body AdoptCandidatesAsNotesAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdoptCandidatesAsNotesAction overwrites any union data inside the ActionRequest as the provided AdoptCandidatesAsNotesAction
func (t *ActionRequest) FromAdoptCandidatesAsNotesAction(v AdoptCandidatesAsNotesAction) error {
	v.Kind = "adopt-candidates-as-notes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdoptCandidatesAsNotesAction performs a merge with any union data inside the ActionRequest, using the provided AdoptCandidatesAsNotesAction
func (t *ActionRequest) MergeAdoptCandidatesAsNotesAction(v AdoptCandidatesAsNotesAction) error {
	v.Kind = "adopt-candidates-as-notes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRepairAction returns the union data inside the ActionRequest as a RepairAction
func (t ActionRequest) AsRepairAction() (RepairAction, error) {
	var body RepairAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRepairAction overwrites any union data inside the ActionRequest as the provided RepairAction
func (t *ActionRequest) FromRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRepairAction performs a merge with any union data inside the ActionRequest, using the provided RepairAction
func (t *ActionRequest) MergeRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolveAction returns the union data inside the ActionRequest as a SolveAction
func (t ActionRequest) AsSolveAction() (SolveAction, error) {
	var body SolveAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolveAction overwrites any union data inside the ActionRequest as the provided SolveAction
func (t *ActionRequest) FromSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolveAction performs a merge with any union data inside the ActionRequest, using the provided SolveAction
func (t *ActionRequest) MergeSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ActionRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "adopt-candidates-as-notes":
		return t.AsAdoptCandidatesAsNotesAction()
	case "apply-hint":
		return t.AsApplyHintAction()
	case "clear-value":
		return t.AsClearValueAction()
	case "redo":
		return t.AsRedoAction()
	case "repair":
		return t.AsRepairAction()
	case "reset":
		return t.AsResetAction()
	case "set-notes":
		return t.AsSetNotesAction()
	case "set-value":
		return t.AsSetValueAction()
	case "solve":
		return t.AsSolveAction()
	case "undo":
		return t.AsUndoAction()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ActionRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDifficultySource returns the union data inside the CreateSessionRequest_Source as a DifficultySource
func (t CreateSessionRequest_Source) AsDifficultySource() (DifficultySource, error) {
	var body DifficultySource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDifficultySource overwrites any union data inside the CreateSessionRequest_Source as the provided DifficultySource
func (t *CreateSessionRequest_Source) FromDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDifficultySource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided DifficultySource
func (t *CreateSessionRequest_Source) MergeDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPuzzleSource returns the union data inside the CreateSessionRequest_Source as a PuzzleSource
func (t CreateSessionRequest_Source) AsPuzzleSource() (PuzzleSource, error) {
	var body PuzzleSource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPuzzleSource overwrites any union data inside the CreateSessionRequest_Source as the provided PuzzleSource
func (t *CreateSessionRequest_Source) FromPuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePuzzleSource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided PuzzleSource
func (t *CreateSessionRequest_Source) MergePuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateSessionRequest_Source) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateSessionRequest_Source) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "difficulty":
		return t.AsDifficultySource()
	case "puzzle":
		return t.AsPuzzleSource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateSessionRequest_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateSessionRequest_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(w http.ResponseWriter, r *http.Request)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportSession operation middleware
func (siw *ServerInterfaceWrapper) ImportSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyAction(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportSession operation middleware
func (siw *ServerInterfaceWrapper) ExportSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewHint operation middleware
func (siw *ServerInterfaceWrapper) PreviewHint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewHint(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions", wrapper.ListSessions)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions", wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/import", wrapper.ImportSession)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/{sessionId}/actions", wrapper.ApplyAction)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/export", wrapper.ExportSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/hint", wrapper.PreviewHint)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type PayloadTooLargeJSONResponse Error

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedJSONResponse struct {
	Body Error

	Headers UnauthorizedResponseHeaders
}

type UnprocessableEntityJSONResponse Error

type UnsupportedMediaTypeJSONResponse Error

type ListSessionsRequestObject struct {
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse SessionList

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessions401JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListSessions500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListSessions500JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201ResponseHeaders struct {
	Location string
}

type CreateSession201JSONResponse struct {
	Body    Session
	Headers CreateSession201ResponseHeaders
}

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSession401JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response CreateSession413JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateSession415JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateSession422JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportSessionRequestObject struct {
	Body *ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
}

type ImportSessionResponseObject interface {
	VisitImportSessionResponse(w http.ResponseWriter) error
}

type ImportSession201ResponseHeaders struct {
	Location string
}

type ImportSession201JSONResponse struct {
	Body    Session
	Headers ImportSession201ResponseHeaders
}

func (response ImportSession201JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportSession400JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportSession401JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ImportSession413JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ImportSession415JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ImportSession422JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportSession500JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSession401JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteSession404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSession404JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSession500JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse Session

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSession401JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSession404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSession404JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSession500JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyActionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
	Body      *ApplyActionJSONRequestBody
}

type ApplyActionResponseObject interface {
	VisitApplyActionResponse(w http.ResponseWriter) error
}

type ApplyAction200JSONResponse ActionResponse

func (response ApplyAction200JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction400JSONResponse struct{ BadRequestJSONResponse }

func (response ApplyAction400JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ApplyAction401JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ApplyAction404JSONResponse struct{ NotFoundJSONResponse }

func (response ApplyAction404JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction409JSONResponse RevisionConflict

func (response ApplyAction409JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ApplyAction413JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ApplyAction415JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ApplyAction422JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction500JSONResponse struct{ InternalErrorJSONResponse }

func (response ApplyAction500JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type ExportSessionResponseObject interface {
	VisitExportSessionResponse(w http.ResponseWriter) error
}

type ExportSession200ResponseHeaders struct {
	ContentDisposition string
}

type ExportSession200ApplicationVndSudokuSessionPlusJSONResponse struct {
	Body    openapi_types.File
	Headers ExportSession200ResponseHeaders
}

func (response ExportSession200ApplicationVndSudokuSessionPlusJSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.sudoku.session+json")
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportSession401JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession404JSONResponse struct{ NotFoundJSONResponse }

func (response ExportSession404JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportSession500JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHintRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type PreviewHintResponseObject interface {
	VisitPreviewHintResponse(w http.ResponseWriter) error
}

type PreviewHint200JSONResponse HintPreview

func (response PreviewHint200JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PreviewHint401JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type PreviewHint404JSONResponse struct{ NotFoundJSONResponse }

func (response PreviewHint404JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response PreviewHint422JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint500JSONResponse struct{ InternalErrorJSONResponse }

func (response PreviewHint500JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth400JSONResponse struct{ BadRequestJSONResponse }

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetHealth500JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(ctx context.Context, request ImportSessionRequestObject) (ImportSessionResponseObject, error)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(ctx context.Context, request ApplyActionRequestObject) (ApplyActionResponseObject, error)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(ctx context.Context, request ExportSessionRequestObject) (ExportSessionResponseObject, error)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(ctx context.Context, request PreviewHintRequestObject) (PreviewHintResponseObject, error)
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request) {
	var request ListSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportSession operation middleware
func (sh *strictHandler) ImportSession(w http.ResponseWriter, r *http.Request) {
	var request ImportSessionRequestObject

	var body ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportSession(ctx, request.(ImportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportSessionResponseObject); ok {
		if err := validResponse.VisitImportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request DeleteSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request GetSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyAction operation middleware
func (sh *strictHandler) ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ApplyActionRequestObject

	request.SessionId = sessionId

	var body ApplyActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyAction(ctx, request.(ApplyActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyActionResponseObject); ok {
		if err := validResponse.VisitApplyActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportSession operation middleware
func (sh *strictHandler) ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ExportSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportSession(ctx, request.(ExportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportSessionResponseObject); ok {
		if err := validResponse.VisitExportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewHint operation middleware
func (sh *strictHandler) PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request PreviewHintRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewHint(ctx, request.(PreviewHintRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewHint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewHintResponseObject); ok {
		if err := validResponse.VisitPreviewHintResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8a3MTObZ/RdV3vm27E4cAIVP3QwZYoJZhuISZqVqSS8ndx7aWbqlHUicxKf/3W0dS",
	"q9UPx+4kwMJevhDbepy3zkNH11EqilJw4FpFx9dRSSUtQIM0n05BKSb4qww/ZKBSyUrNBI+Oo99K+lcF",
	"RFKeiYIoO5CwDLhmcwYyIa80YYpwoQklqQTzC82TKI4YLlBSvYziiNMCouNI+Z3iSMJfFZOQRcdaVhBH",
	"Kl1CQRGEnyTMo+Pov/YaoPfsr2qvgXW9XuMiqhRcgcHjF5q9g78qUBo/pYJr4OZPWpY5SynitPcvhYhd",
	"R3BFizIH86eUQtopGULJ+AXNWTaRbrE4mjPIM4RfVDKFKI4KUIouwH9FikppoiCHVBO4oqnOV0RwIKoq",
	"SyE1ZOQT4wj0rog+N0AZJNsseb8E4iBDyhc0nwtZQEaEJBdM5FSDInoJREvKFW5OkBSSpjqJ1nH0imuQ",
	"nObPG6xvTyi71MT+EJJFB1CmosozIyIzIIhqDhruhRYnnFQcrkpItSVAVkk6YznTKzKnLK8kEJGmlZSQ",
	"kUuml6LSJAf6ifEFqaFXhixvhP67qHh2N4o4AZ9woSdzs1xLVpz+XFKrMXbE/coEZF5NMwF2H7hiyjL/",
	"LV3lgmbvhXhN5QLuhmxpF5toISa5WS5Etub+TGQrAlcpQGblsqBXrKgKothnuG+FCPdJBZ+zRYWsNzDk",
	"rGCWCr9zWumlkOwz3JHfVbhSiP0MqARJ8Fe0iHZF1Fdv9u5D/P1qxO3XWGBjG5hSKOlCEmfT0C4vgWbO",
	"8v/555+TkwZEg2IDUyo4mtLoF7N2FEd6VRox1pLxBQJkaFlKkSLesxyec830aneSGiCALxiHd/AvSC1e",
	"19EFzasOvSHP7bp5VfDo+EEcSXEZHU/XsbdGRVFphGJiBofcSClHPUiXlC+AUFJKMcuhIGagQcPRxx0v",
	"G2BoHw9OzToaLhnNURq8FprBlv1okgzn7/8YuIQ8J+4gmFWaOIxnQAz5IXOC78+jXyFj9L1h6N0UwK84",
	"KXDJiRGSTUfBU7vRBDeu/Qa/wH0bgxs3I7MV0UumiChBGnSTYH8jmCdGHv/B7KEAvCqi4w+RAj2xshFH",
	"aQ5U+k8SFKC3UPFMmI/mPyToarJkHH/CyVxoUOb3kjJUKyXyC4jOe/oVOwgCpyZjiGzBONWWDQUtSxyM",
	"nMtEqScp5RnKG6gJVW6vDUQ8wQlP/fgT9QZH2z3bgG9aAEe8ZFz7OSFBNkx6ikP+wBF+lqHUhuHvIBPB",
	"QEOyjUPx12AwsmPjWAUN2A1bNrqduk2cRgo2z2gjabm8aTT+6IcaAdow8nfu6bGOo1Ki+OrVG+tfWx8z",
	"jgSH3+bR8YdtvnQLxHV88/Ae47ZNCGm8bWwLrW3L7jy0K6DbxnfYvHX5mxRoOxqBtG4FLJCP9XlgGWz4",
	"Y9U/Y/gdzd9aoWAoznOaK/BywuyJK0FVud5mY/0WONbEWhesPhxvRsyNQ2vKaamWYutep/W4dRxdUskZ",
	"X6h+NPpG8MmcapqTjNEFF0qzVOFhnlUpZITONUjj+i1oAYQa+I2zTdMUSg3G/WEaCrN2z9q6L6iUdBXZ",
	"6LIOUT802AdIxTUlG9stZujGhLa7JvUI/lDvCG3nzz+cyqeUf7R21GM2EyIHyutfrVUZ/NX4RWZrT50b",
	"LQHk+VMzB2cX9OqVnXU07RIxjuz5cfN6qKFGWjTV1dbdX9ACTu3ILpOoP4ccRn7NgAQBrQb5dpNSj+Nj",
	"7aziMW1inuj4SRwVjNu/G2phKLoAidvX0ezH26jbJ+YDWOO5b3YJBpwN40+PAdV7yDeB94wtmO4xqo+l",
	"A96CEdekqzcZZFTHuI/jzf3SOfTxulHSjpgPofiL1dEXkmU7K6eb805ctpXTsrP50FXUYF64Vd9a7L5k",
	"YCdGGkC05LtYIeOO4FYzmAsJo6bcRjtd7PfRA9gnTz2kgag/xujgx52wNPpzCrqZthuq4byRmt09+doK",
	"6baPHZN6CHeJ1AG7jfyQ0COT3grFvpLBvUfibMLmj9pQtt2Zf4IUREKJgQrXilBOoCj1yqQl0FUZhGl/",
	"CImeb/6dHVTtQPquR9MtD5tB9kmgGlxaKAjERxDXFQ22RO8Zm89ZWuV6tVmj6xGndRmirD5/zjcGlW/N",
	"r27wXYPF3u7bQpb27uddpjiqDNH8WUCKJu8CVK1MXiljVRHF0ZJK5CAyV+KxCxcsH0yi9CAfx76sBc1u",
	"JBoS8WCdbT6CE85gxjCZ0LMapbP+UNjVmXDeW+fQb53zcVRx9lcF7mctKwh2GuW61JNG+y7hxLGbjdvJ",
	"V83GuJr1nK0ZzWegKcv7BswsMCQDZtZTk4ptNKVfv6y/MQndeHPSdqii0ylxzIWcsSwDPhGSLZjNhfWL",
	"XrWpnaSCz3OWhlA0ifP6Gx+31V+4DH4vpY++g9mH5rm4NABxMXFhHRcTl3PlonbGS5CKKQ08hYlLv8fd",
	"uuWQ0QjZMfIsdZWKbX6od3F8BWMHATGsXvuCtNH918AXehkdT/f3jfD6zwNo+ax8d+a2qR2JNAA3yw2J",
	"ZhCmt2RzUkqxkKBUw+46O5oNsuIl0ByBGnfo+p1r+7s0y2w3vm7mEEovXS7jS3ukQF3hZRyPbhHCa0iX",
	"xnrfQpbuEP4PxvghNJ4Im9jwFg0MXI7kxphk1Hi3dnPG0Ow7hMobcSIXVQFc/wdkMxpkgxT+N8TTHRZf",
	"CMMgu/9NcXRFxi+EZVPh+aZI2sLrF8ExLL18Qxxt+fAL4RhU374his6Nu0cMWzHoOMy6wLlQe+AcrIPw",
	"6/7ltKOpcVyJHfIzyYQmQpLPOyR+6pP3aNo6iPFjSTX6r9Fx9L8f9idPkvPro+n6p12jSgfuELl+VLP8",
	"IxvjH9cEvwvAmgtZUG1910eH0bZ0aD31aR18jnTaKymB61sRxgf7NM93SKu1wv74uhc9ZNCmcj+q7lO8",
	"Q8nzW9XhB1MQcZ80wdpDTAwu1I1ggM0Z7XgP/GvdTOhQhIVpjh3JYK/YN5cfP0TF6eHh7NfHV2+elP+T",
	"HvyhXz+6fHZ0gmsEZ8Cjw9YZcHDQPgNOJv+kk8/7kycfJ+d/+2noiHLbv2bjk9d25u53A9xWp1VRULlq",
	"J9dsDHvjNQu/3w1UrNf+wjKViguQMNAU8V5WQC6XwM1dE2WhMfdMMqbcLDKXorDX0XMgbrEVoZooTaWu",
	"yqThU1AYvJUkj741EUdVmVG0w1S3rCt+OdGs2O5o9qS/vmYRrBwScZid+ju+WxFe5bynuxQjctZ3u0+x",
	"Sb30d1xCDO/lfvd3W06D02kME+5yCczfEtpVCk1tZx1HC3YBfOssI1r1lDrxu9tdlnqWu6I7DrrbmMfd",
	"tDHAqCMCjiJ+oTDTXduMgN63uKX242YlftRcRCMtu7pSZsboWqifNeY2p78Utes+qFiQVpLp1SmuY1lg",
	"u5BOKluusZ/+XjsXwvSSTrT4BEiotk/1rm5kQr8KLtw9XgUS/2QqbOaai1ZfFWTmeq9S6FEZnJr+q4aD",
	"S63LutNnLgZ8uiWQ0yoTnyry8v37t+Tk7SsCV6VQrpnStNAxvrBXi23LEtGC5CKlOdFC5IpQnp1xBSWV",
	"VEO+IhmUuVhBRtKcIcUT8r6Fk6uraqrZBRi00AxAfMZreVJx0D4U4wbelUzO+BkP1stNlVMRwUkuRDmj",
	"6ScyQxjmtMp1Qn4zbS5CIjpUN/Qk9IxzwSd+kl0IpG1ppbkSweDBtraEPLUInnG1NL2eCnhG6EBTWshd",
	"Jh2FCuC67mRDBCA5QwHJWQrubnvTcBwdR7++et90FOMHlMU6JIhOWkR1LDVMq0MLgvQzXEbxYNpcoOnw",
	"Hk03SGtEommyn+ybmzIlcFqy6Dh6kEyTqSmY66WR/D1asr2L6V4YLy3sRYuuoOtKckVmouIZZC58YGDE",
	"h1jiSDembiFzZXkj4b5dCWPJCCO603rLTjv0wf7+Dr1do9quTQA50HXlfg6QETIzYdBsRQqhkL0pcJ2v",
	"iIsPyJxJ15N6uD/dtL3HZ6/VsrmOo4cWuZsntVud1y05QVRMi8AFhHrVNO4Zv54uTJTuSXy+jqNS2Ci6",
	"zYnWRTHX3g5K/yKysf2Qs1X7AlQD8wvUS6qBCElQIEzimKoV8clp77aGl86Ci2XuEpU97cKfDFNnq7c+",
	"l93seooBq41nqemfyxlkN27plvdD/DW1JHmQHCSPkuQJ/vUwSaZJMj1KHh0mSZIcTZODJ0nyOLH/jpLk",
	"0ePk6AD/PniUPHlovjpIHpjZD5Mp/jWql3LwLt+6fai760sdRZretyJtal0MO8RTA25GKGqPPQ9M5aDT",
	"w/taWECGTE1ureDv714TMTfnGIfLehN/XlL7JIRPKHVt2d7WDJPB5nAXlQzeaLit6h9OH2yf1G10N/Me",
	"7rLZQIcsTj442GVyvxf6PmyVFVzUPiceThkb/UWL0FSo+lZrHfdOqD1WIJ6G986idcVHaYEnMvWHlTsT",
	"W28MpKaCaH2bVs8/M54TekTtoYRpBfn8ZyOP6GfZQ8/2aOFuSzww5iwHtVIaCoKHrHUJ2ib3lUFgrMm9",
	"4FmizGmfOMj+1ldhNzdoku7rfNzkzWaMI6fi9hWaw6OHjx8N6Mq/kb2xMhDwEw2PcznR9PCMFDSDOpF5",
	"J9PT3ev/7c/3Yn+sohn74583CF3q3W3OtX8BaG2FJgf76kRbs5+Z70PNbqnH4XD8VsswSq3g+QoNTZN6",
	"xz9kRi5BArH7Zrd3Pw8tDDdP8k/K3AcPnjGVUpkFhwCiOYDhJrfVRSNtQr8AvZHK+1/LCLmaokfMezuI",
	"YQaapku0Gi4l+j0x7R3QzNi+dqhfI2rC/YBfL2gBZU5XNswI3ujaUERuhoS1q/Mtirdnb1v3HgIbt0m8",
	"wWt4b5Il7kUmz8lSiguWYVxYalYwpVlKUsEt59OVfaFK5Al5jpJ8xuuGbVJU2j2dw1MJhbkuYx8UcSs3",
	"j22lkBD7iow9uc640jSv+8AVyYEi7bVxpXgAXMVtu3A25GSYe5nBmxK3jeqUK660npapiybTwVrIvg/U",
	"wtqGffbGx12HKHF1Vr95s6a/2gO/mhk9Im5qv0KykwNzf7aj89DBBhMy0OtvrYfxW1akbgOoTf5X8hTG",
	"GpzD/Sf3RrjeHZgNpOsrK1PEaE7yn+ntGI03j/ehl5mFj0kM2+pt9hau6kDrxowgmrWgXaWJl2iTLZyt",
	"NKjYPbdo4iQTHPWs1vOrbmi0s3r+O8RHfSm9IfJsxyT1o0/PmCqDJuJOvrJaLOxbeZm45CaVhvEmpwW0",
	"oxL/8lVENfohuOHPfux/n0WWUnVLU4KIn0UbA5TvwmmxsmPEMaR692GzjenRL+a31N0bg56sawh5absW",
	"vthxFPaeDL7Ih0CaWo4OPNvatNZZksbQNr7HVzxlvqV1dcRD84WUqh/ltH4eX7iyX1fC7tEztn1gnzcK",
	"0gvQruPsVmIUvJVX3zzwrWc7e1wOgA220DEGxcetfFuv5rbcdJXf6PjDeStPuYT0kwdvWVOxZqLD6nzd",
	"WeN6HbdLxx/OMb6whU3L4zYRntmiZlPobOqIURxVMncF3+O9venB42Q/2U+mx0f7R/smbnHgdBd1Psxk",
	"LgH6OLhyY82YuAeSu+nXDvRadcdmFW8v++uc+hiYZrYkiGtMXMG5jtz8Sl4v1ufr/wsAAP//Ju+OVuVZ",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
